/* Generated By:JavaCC: Do not edit this line. ParserMonedasConstants.java */
package com.tallerLenguaje1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserMonedasConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MONEDA = 5;
  /** RegularExpression Id. */
  int VALOR = 6;
  /** RegularExpression Id. */
  int DIA = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<MONEDA>",
    "<VALOR>",
    "<DIA>",
  };

}
