/* Generated By:JavaCC: Do not edit this line. ParserVariacionesConstants.java */
package com.tallerLenguaje1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserVariacionesConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIA = 5;
  /** RegularExpression Id. */
  int NUMERO = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIA>",
    "<NUMERO>",
    "\",\"",
  };

}
